version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/files_api
    working_dir: /files_api
    command: /bin/sh -c "rm -f /files_api/tmp/pids/server.pid && bundle exec rdebug-ide --server-mode --debug --host 0.0.0.0 --port 1234 -- bin/rails s -b 0.0.0.0"
    restart: always
    ports:
      - 3000:3000
      - 1234:1234
      - 26162:26162
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10-alpine