version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/files_api
    working_dir: /files_api
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10-alpine